version: "3.3"

services:
  pg:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: pg
    volumes:
      - pg:/var/lib/postgresql/data


  g_sheets:
    build: .
    command: poetry run python main.py
    container_name: api_app
    volumes:
      - .:/g_sheets/
    depends_on:
      - pg
    env_file:
      - .env

volumes:
  pg:
   driver: local